### ISSUE TITLE
Module suggestion - FoodServ (aka BurgerBot)

### ISSUE THREAD

**Issue by jufineath** [averetzi/shuriken#1]
As a user of IRC services i often find myself hungry, but chained to my laptop engaged in stimulating conversation. This leaves me in a quandary unable to prepare or retrieve food. 

For MVP behavior, please support an IRC command that connects to foodserv, sends a confirmation notification to my phone, then places a standard Burger King Order. (Large Whopper meal, no pickle, diet coke, onion rings and a 10 piece with zesty sauce.)

This service should be kept simple. Users would be able to configure only one active meal at a time. Remember, this is primarily a low-cost way to solve the mid-chat hunger pangs. Don’t add features.

**Comment by rakaur** [comment]
I have this same problem.

**Comment by dbdii407** [comment]
After using these services for a long time, I too have been having this same problem. Please implement.

**Comment by averetzi** [comment]
I think this service would do more harm than good to the average IRC user.

To begin with, [worldwide obesity has nearly tripled since 1975.](https://www.who.int/news-room/fact-sheets/detail/obesity-and-overweight) I expect most IRC users to be more technically literate than the average internet user, more than likely a good portion of them are employed in a field where computers play a key role in their work (e.g. computer programmer, systems analyst). Because these are a group of people who likely sit for long periods of time and don't get enough exercise or eat healthy to maintain a normal weight for their height, I fear that FoodServ would only contribute to the ongoing global uptick in obesity and the [other health consequences associated with it](https://www.cdc.gov/obesity/adult/causes.html#Consequences).

I wouldn't be able to sleep at night knowing full well that my product would allow a person who's likely in ill health to contribute to their poor diet and consequently, their poor and deteriorating health.

Now let me get back to my double quarter pounder with cheese.

**Comment by dbdii407** [comment]
Booooooooooooooooooooooo

**Comment by rakaur** [comment]
Fascist
